language: node_js
node_js:
  - "8"
script: 
  - npm run build
install:
  - npm install
  - npm install -g hexo
cache:
  directories:
    - node_modules
after_script:
  - git remote add upstream https://houko@dev.azure.com/houko/blog/_git/blog
  - git fetch upstream
  - git checkout master
  - git merge upstream/master
  - git push origin master
  - cp -f CNAME ./public/CNAME
  - cd ./public
  - touch README.MD
  - echo `date +"%Y-%m-%d %H-%m-%s"` >> README.MD
  - git init
  - git config user.name "xiaomo"
  - git config user.email "xiaomo@xiaomo.info"
  - git add .
  - git commit -m "automated build"
  - git push --quiet --force https://${REPO_TOKEN}@github.com/houko/blog.git master:gh-pages
