language: node_js
node_js:
  - "8"
script: 
  - npm run build
install:
  - npm install
  - npm install -g hexo
cache:
  directories:
    - node_modules
after_script:
  - cp -f CNAME ./public/CNAME
  - git init
  - git config user.name "xiaomo"
  - git config user.email "xiaomo@xiaomo.info"
  - git add .
  - git commit -m "automated build"
  - git push --quiet --force https://${REPO_TOKEN}@github.com/xiaomoinfo/blog.git master:gh-pages
